[package]
name = "somelse"
version = "0.1.0-rc.1"
edition = "2021"
rust-version = "1.56"
authors = ["Adam Williams"]
description = "extract an Option::Some value or diverge on None"
readme = "README.md"
include = ["/src/**", "/tests/**", "/README.md", "/LICENSE-*"]
repository = "https://github.com/awill1988/somelse"
license = "MIT OR Apache-2.0"
keywords = ["macros", "option", "pattern-matching", "control-flow", "no-std"]
categories = ["rust-patterns", "no-std", "development-tools"]

[features]
default = []

[dev-dependencies]
